apiVersion: v1
kind: Secret
metadata:
  name: repo-{{ .Values.application.name }}
  namespace: argocd
  labels:
    # Эта метка говорит Argo CD что это credentials для репозитория
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: {{ .Values.repository.url }}
  username: {{ .Values.repository.username }}
  password: {{ .Values.repository.password }}
